config/routes.rb
Crowdfunder::Application.routes.draw do
  root "projects#index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :projects
  resources :pledges, :only => [:new, :create]
  resources :users, except: [:index]
  resources :sessions
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates_presence_of :user
  validates_presence_of :project
  validates_numericality_of :amount, :greater_than => 0
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pledges
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :projects
  has_many :pledges

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def new
    @pledge = Pledge.new
  end

  def create
    @pledge = Pledge.new(params[:pledge])
      if @pledge.save
        redirect :back
      else
        flash[:alert] = "Try again"
      end
  end

  def destroy
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Bye"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, :notice => "Account created"
    else
      flash.now.alert = "Try again"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email, 
      :first_name, 
      :last_name, 
      :password
    )
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">CrowdFunder</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="<%='active' if current_page? root_path %>">
              <%= link_to 'Home', :root %>
            </li>
            <li class="<%='active' if params[:controller] == 'projects' and !current_page?(root_path) %>">
              <%= link_to 'Projects', :projects %>
            </li>
            <li>
              <% if current_user %>
              <%= link_to "Logout", logout_path %>
              <% else %>
              <li <%= yield(:li_signup_class) %>>
                <%= link_to "Sign Up", new_user_path %>
              </li>
              <li <%= yield(:li_login_class) %>>
                <%= link_to "Login", new_session_path %>
              </li>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container page">
    <% if flash[:notice] %>
    <div class="alert alert-block">
      <p id="notice"><%= flash[:notice] %></p>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="alert alert-block">
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <% end %>


    <%= yield %>
  </div>

</body>
</html>

app/views/pledges/new.html.erb
<h1>Pledges</h2>

<%= form_for @pledge do |f| %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
<div class="container"> 
  <%= f.submit %>
<div>
<% end %>

app/views/projects/index.html.erb
<% provide(:li_projects_class, "class=active") %>
<div class="container">
<h3>Listing projects</h3>

<ul>
  <% @projects.each do |project| %>
  <li class="well">
    <h4><%= link_to "#{project.title}", project_path(project) %></h4>
  </li>
  <% end %>
</ul>

</div>

app/views/projects/show.html.erb
<% provide(:li_projects_class, "class=active") %>
<h1><%= @project.title%></h1>

app/views/users/new.html.erb
<% provide(:li_signup_class, "class=active") %>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.submit "Create Account" %>
<% end %>